/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#002114",
        "inverse-surface": "#2e312f",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e1e3df",
        "tertiary-container": "#8d4d4e",
        "on-error": "#ffffff",
        "surface-variant": "#e1e3df",
        "on-tertiary-fixed-variant": "#6f3537",
        "on-tertiary-container": "#ffcfce",
        outline: "#707973",
        "on-surface": "#191c1a",
        "primary-fixed": "#b1f0ce",
        "surface-container-low": "#f2f4f0",
        "tertiary-fixed-dim": "#ffb3b3",
        "on-primary-fixed-variant": "#0e5138",
        error: "#ba1a1a",
        "secondary-fixed": "#ffdcbc",
        "surface-tint": "#2c694e",
        "tertiary-fixed": "#ffdad9",
        "on-primary-container": "#a8e7c5",
        background: "#f8faf6",
        "on-secondary-fixed": "#2c1700",
        "surface-dim": "#d8dbd7",
        "primary-container": "#2d6a4f",
        "error-container": "#ffdad6",
        "inverse-primary": "#95d4b3",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eff1ed",
        secondary: "#895100",
        "on-secondary": "#ffffff",
        "outline-variant": "#bfc9c1",
        "secondary-fixed-dim": "#ffb86b",
        "surface-bright": "#f8faf6",
        "on-error-container": "#93000a",
        primary: "#0f5238",
        "surface-container": "#eceeea",
        "on-surface-variant": "#404943",
        tertiary: "#713638",
        "secondary-container": "#fd9d1a",
        "on-background": "#191c1a",
        "surface-container-high": "#e7e9e5",
        "on-secondary-container": "#663b00",
        "on-tertiary-fixed": "#390b0e",
        surface: "#f8faf6",
        "on-secondary-fixed-variant": "#683d00",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#95d4b3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        xl: "80px",
        gutter: "24px",
        md: "24px",
        base: "8px",
        lg: "48px",
        container_max: "1280px",
        sm: "12px",
      },
      fontFamily: {
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        h1: ["Plus Jakarta Sans", "sans-serif"],
        h3: ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        h2: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        h1: ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        h2: ["36px", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
};
